---
title: "Team_Essay_2"
author: "Sahil, Ariel, Ilya, Lekha, Anthony, Trang"
date: "3/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction




## Formula and Basics




## Loading required R packages

readxl: to read data from xl sheet
tidyverse: for data manipulation and visualization

```{r}
library("readxl")
library("tidyverse")
```

## Examples of data
```{r}
bball_data <- read_excel("C:/Users/ariel/Desktop/TeamEssay2/Basketball.xlsx")
bball_data <- bball_data %>%
  rename(
    "height" = "X1",
    "weight" = "X2",
    "FGP" = "X3",
    "FTP" = "X4",
    "PPG" = "X5"
  )
head(basketball, 30)


{r}
FGP_Model <- lm(FGP ~ ., data = bball_data)
#Summary of the model
summary(FGP_Model)
summary(FGP_Model)$coefficient

#Confidence Interval of the model coefficients
confint(FGP_Model)

#Coefficient of determination
summary(FGP_Model)$r.squared


#RSE
sigma(FGP_Model)/mean(bball_data$FGP)
plot(FGP_Model)


{r}
FGP_Model2 <- lm(FGP ~ height + weight + PPG, data = bball_data)
#Summary of the model
summary(FGP_Model2)
summary(FGP_Model2)$coefficient

#Confidence Interval of the model coefficients
confint(FGP_Model2)

#Coefficient of determination
summary(FGP_Model2)$r.squared


#RSE
sigma(FGP_Model2)/mean(bball_data$FGP)
plot(FGP_Model2)

{r}
FGP_Model3 <- lm(FTP ~ height + weight, data = bball_data)
#Summary of the model
summary(FGP_Model3)
summary(FGP_Model3)$coefficient

#Confidence Interval of the model coefficients
confint(FGP_Model3)

#Coefficient of determination
summary(FGP_Model3)$r.squared


#RSE
sigma(FGP_Model3)/mean(bball_data$FGP)

plot(FGP_Model3)
```

## Building model

```{r}
model <- lm(AveragePointsScored ~ Height + Weight + GoalsPercentage + ThrowsPercentage, data = basketball)
summary(model)
```

## Interpretation

```{r}
confint(model)
```


## Model accuracy assessment



## Read also



## Discussion




## References


